bundler_args: --without development
language: ruby
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: rbx-19mode
    - rvm: ruby-head
rvm:
  - rbx-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
