language: ruby

sudo: false

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

bundler_args: --without development --jobs=3 --retry=3

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
